#!/bin/sh
#
# Runs all encoding tests that have not been run, or are missing data.
#
# Argument: Filenames.

set -e

for sourcefile in $@; do

  # filename format: <path>/<clip_name>_<width>_<height>_<frame_rate>.yuv
  pathless=$(basename ${sourcefile})
  clip_stem=${pathless%.*}

  echo "Clip $clip_stem"
  # Detecting test dirs by looking for the file name "measurer". Somewhat
  # fragile.
  for measurer in */*/measurer; do
     dir=$(dirname $measurer)
     ./run_one_test $dir $sourcefile
  done
done
